import Head from "next/head";
import styles from "../styles/Home.module.css";
import Hero from "../components/Hero";
import Content from "../components/Content";
import CTA from "../components/CTA";
import Testimonial from "../components/Testimonial";
import Footer from "../components/Footer";
import Article from "../components/Article";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero />
      <Content />
      <CTA />
      <Article />
      <Testimonial />
      <Footer />
    </div>
  );
}
